server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${USER_MYSQL_URL:jdbc:mysql://localhost:3306/user_db}
    username: ${USER_MYSQL_USERNAME:root}
    password: ${USER_MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  data:
    redis:
      host: ${USER_REDIS_HOST:user-redis}
      port: ${USER_REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:example@test.com}
    password: ${MAIL_PASSWORD:123}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
            required: ${MAIL_STARTTLS_REQUIRED:true}
          connectiontimeout: ${MAIL_CONNECTION_TIMEOUT:5000}
          timeout: ${MAIL_TIMEOUT:5000}
          writetimeout: ${MAIL_WRITE_TIMEOUT:5000}
    auth-code-expiration-millis: ${MAIL_AUTH_CODE_EXPIRATION_MILLIS:1800000}

jwt:
  secret: ${JWT_SECRET:kt-cloud-tech-up-final-project-2026020201010101}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:300000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:43200000}

oauth:
  front:
    callback: ${FRONT_OAUTH_CALLBACK:http://localhost:8081/test/callback}
  kakao:
    client-id: ${KAKAO_CLIENT_ID:kakao_client_id}
    client-secret: ${KAKAO_CLIENT_SECRET:kakao_client_secret}
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/kakao/callback}
    token-url: ${KAKAO_TOKEN_URL:https://kauth.kakao.com/oauth/token}
    authorization-url: ${KAKAO_AUTHORIZATION_URL:https://kauth.kakao.com/oauth/authorize}
  naver:
    client-id: ${NAVER_CLIENT_ID:naver_client_id}
    client-secret: ${NAVER_CLIENT_SECRET:naver_client_secret}
    redirect-url: ${NAVER_REDIRECT_URI:http://localhost:8080/api/auth/naver/callback}
    token-url: ${NAVER_TOKEN_URL:https://nid.naver.com/oauth2.0/token}
    authorization-url: ${NAVER_AUTHORIZATION_URL:https://nid.naver.com/oauth2.0/authorize}

springdoc:
  api-docs:
    path: /api/auth/v3/api-docs
