server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: kimdohyun032@gmail.com
    password: bxsg aoia bgkw nkpv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000

jwt:
  secret: ${kt.jwt.secret:kt-cloud-tech-up-final-project-2026020201010101}
  access-token-expiration: ${kt.jwt.access-token-expiration:300000} # 5
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration:43200000} # 12

springdoc:
  api-docs:
    path: /api/auth/v3/api-docs