server:
  port: 8080

spring:

  data:
    redis:
      host: ${USER_REDIS_HOST:user-redis}
      port: ${USER_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      server:
        webflux:
          routes:
            # api-docs (Swagger)
            - id: auth-docs
              uri: ${AUTH_SERVER_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/v3/api-docs
            - id: payment-docs
              uri: ${PAYMENT_SERVER_URI:http://localhost:8082}
              predicates:
                - Path=/api/payments/v3/api-docs
            - id: queue-docs
              uri: ${QUEUE_SERVER_URI:http://localhost:8083}
              predicates:
                - Path=/api/queue/v3/api-docs
            - id: ticketing-docs
              uri: ${TICKETING_SERVER_URI:http://localhost:8084}
              predicates:
                - Path=/api/ticketing/v3/api-docs/ticketing
            - id: booking-docs
              uri: ${TICKETING_SERVER_URI:http://localhost:8084}
              predicates:
                - Path=/api/ticketing/v3/api-docs/booking
            - id: musical-docs
              uri: ${MUSICAL_SERVER_URI:http://localhost:8085}
              predicates:
                - Path=/api/musical/v3/api-docs

            # service
            - id: auth-jwt
              uri: ${AUTH_SERVER_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/logout
              filters:
                - JwtAuthenticationFilter
            - id: auth
              uri: ${AUTH_SERVER_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
            - id: auth-test
              uri: ${AUTH_SERVER_URI:http://localhost:8081}
              predicates:
                - Path=/test/**
            - id: payment
              uri: ${PAYMENT_SERVER_URI:http://localhost:8082}
              predicates:
                - Path=/api/payments/**
            - id: payment-webhook
              uri: ${PAYMENT_SERVER_URI:http://localhost:8082}
              predicates:
                - Path=/api/webhooks/**
            - id: queue
              uri: ${QUEUE_SERVER_URI:http://localhost:8083}
              predicates:
                - Path=/api/queue/**
              filters:
                - JwtAuthenticationFilter
            - id: ticketing
              uri: ${TICKETING_SERVER_URI:http://localhost:8084}
              predicates:
                - Path=/api/ticketing/**
              filters:
                - JwtAuthenticationFilter
            - id: booking
              uri: ${TICKETING_SERVER_URI:http://localhost:8084}
              predicates:
                - Path=/api/bookings/**
            - id: musical
              uri: ${MUSICAL_SERVER_URI:http://localhost:8085}
              predicates:
                - Path=/api/musical/**



jwt:
  secret: ${kt.jwt.secret:kt-cloud-tech-up-final-project-2026020201010101}
  access-token-expiration: ${kt.jwt.access-token-expiration:300000} # 5
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration:43200000} # 12

springdoc:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    urls:
      - name: "01-Auth Service"
        url: /api/auth/v3/api-docs
      - name: "02-Payment Service"
        url: /api/payments/v3/api-docs
      - name: "03-Queue Service"
        url: /api/queue/v3/api-docs
      - name: "04-Ticketing Service"
        url: /api/ticketing/v3/api-docs/ticketing
      - name: "05-Booking Service"
        url: /api/ticketing/v3/api-docs/booking
      - name: "06-Musical Service"
        url: /api/musical/v3/api-docs
