server:
  port: 8080

spring:

  data:
    redis:
      host: ${USER_REDIS_HOST:user-redis}
      port: ${USER_REDIS_PORT:6379}

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "*"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      server:
        webflux:
          routes:
            - id: auth-jwt
              uri: ${AUTH_SERVER_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/logout
              filters:
                - JwtAuthenticationFilter
            - id: auth
              uri: ${AUTH_SERVER_URI:http://localhost:8081}
              predicates:
                - Path=/api/auth/**
            - id: auth
              uri: ${AUTH_SERVER_URI:http://localhost:8081}
              predicates:
                - Path=/test/**
            - id: payment
              uri: ${PAYMENT_SERVER_URI:http://localhost:8082}
              predicates:
                - Path=/api/payments/**
            - id: payment-webhook
              uri: ${PAYMENT_SERVER_URI:http://localhost:8082}
              predicates:
                - Path=/api/webhooks/**
            - id: queue
              uri: ${QUEUE_SERVER_URI:http://localhost:8083}
              predicates:
                - Path=/api/queue/**
            - id: ticketing
              uri: ${QUEUE_SERVER_URI:http://localhost:8084}
              predicates:
                - Path=/api/ticketing/**



jwt:
  secret: ${kt.jwt.secret:kt-cloud-tech-up-final-project-2026020201010101}
  access-token-expiration: ${kt.jwt.access-token-expiration:300000} # 5
  refresh-token-expiration: ${kt.jwt.refresh-token-expiration:43200000} # 12

springdoc:
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    urls:
      - name: "01-Auth Service"
        url: /api/auth/v3/api-docs
      - name: "02-Payment Service"
        url: /api/payments/v3/api-docs
      - name: "03-Queue Service"
        url: /api/queue/v3/api-docs

