server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: ticketing

  config:
    import: "classpath:application-observability.yml"

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${TICKETING_MYSQL_URL:jdbc:mysql://localhost:3306/ticketing_db}
    username: ${TICKETING_MYSQL_USERNAME:root}
    password: ${TICKETING_MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      host: ${USER_REDIS_HOST:localhost}
      port: ${USER_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  cloud:
    openfeign:
      client:
        config:
          payment-service:
            url: ${PAYMENT_SERVER_URI:http://localhost:8082}
            connectTimeout: 3000
            readTimeout: 5000

springdoc:
  api-docs:
    path: /api/ticketing/v3/api-docs
  group-configs:
    - group: ticketing
      paths-to-match: /api/ticketing/**
    - group: booking
      paths-to-match: /api/bookings/**

jwt:
  secret: ${JWT_SECRET:kt-cloud-tech-up-final-queue-2026020201010101}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:300000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:43200000}

ticketing:
  active-window-ms: ${TICKETING_ACTIVE_WINDOW_MS:30000}
  session-ttl-sec: ${TICKETING_SESSION_TTL_SEC:300}
