server:
  port: 8082

spring:
  datasource:
    url: ${PAYMENT_MYSQL_URL:jdbc:mysql://localhost:3306/payment_db}
    username: ${PAYMENT_MYSQL_USERNAME:root}
    password: ${PAYMENT_MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect