server:
  port: 8082

spring:
  datasource:
    url: ${PAYMENT_MYSQL_URL:jdbc:mysql://localhost:3306/payment_db}
    username: ${PAYMENT_MYSQL_USERNAME:root}
    password: ${PAYMENT_MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # TODO: 다음 PR에서 update로 변경 필요
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  frontend:
    success-url: /success-temp.html
    fail-url: /fail-temp.html