server:
  port: 8082

spring:
  datasource:
    url: ${PAYMENT_MYSQL_URL:jdbc:mysql://localhost:3306/payment_db}
    username: ${PAYMENT_MYSQL_USERNAME:root}
    password: ${PAYMENT_MYSQL_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

springdoc:
  api-docs:
    path: /api/payments/v3/api-docs

toss:
  payment:
    secret-key: ${TOSS_SECRET_KEY:test_sk_tempKey}
    base-url: https://api.tosspayments.com/v1/payments/