spring:
  application:
    name: musical
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET:truve-media}
        endpoint: ${AWS_S3_ENDPOINT:http://localstack:4566}
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:test}
        secret-key: ${AWS_SECRET_KEY:test}
      stack:
        auto: false
